name: karnote
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  bitsdojo_window: ^0.1.6
  window_manager: ^0.4.3
  flutter_svg: ^2.0.17
  code_text_field: ^1.1.0
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0
  file_picker: ^9.0.0
  provider: ^6.1.2
  encrypt: ^5.0.3
  crypto: ^3.0.6
  archive: ^4.0.2
  path: ^1.9.0
  url_launcher: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3


flutter:
  uses-material-design: true
  assets:
    # icons
    - assets\icons\tabler--arrow-left.svg
    - assets\icons\tabler--arrow-narrow-right.svg
    - assets\icons\tabler--clock.svg
    - assets\icons\tabler--copy.svg
    - assets\icons\tabler--device-floppy.svg
    - assets\icons\tabler--eraser.svg
    - assets\icons\tabler--file.svg
    - assets\icons\tabler--folder-open.svg
    - assets\icons\tabler--menu-2.svg
    - assets\icons\tabler--pencil.svg
    - assets\icons\tabler--search.svg
    - assets\icons\tabler--settings.svg
    - assets\icons\tabler--x.svg
    - assets\icons\tabler--trash.svg
    - assets\icons\tabler--file-plus.svg
    - assets\icons\github-mark.svg

  # illustrations
    - assets/illustrations/abstact.svg

  fonts:
    - family: FiraCode
      fonts:
        - asset: assets\fonts\FiraCode-VF.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets\\logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets\\logo.png"
  windows:
    generate: true
    image_path: "assets\\logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets\\logo.png"