name: karnote
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  bitsdojo_window: ^0.1.6
  window_manager: ^0.4.3
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets\icons\tabler--menu-2.svg
    - assets\icons\tabler--folder-open.svg
    - assets\icons\tabler--search.svg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"